[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "nextcloudfetch"
version = "0.1.1"
description = "Nextcloud file or folder fetcher/downloader"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx",
    "nextcloud-api-wrapper",
    "python-dotenv",
    "tqdm",
    "typer",
]

[project.scripts]
ncfetch = "ncfetch.cli:app"

[tool.hatch.build.targets.wheel]
packages = ["src/ncfetch"]

[tool.typer]
colored = true